name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@1.80.1

    - name: Install clippy
      run: rustup component add clippy
      
    - name: Build
      run: cargo build --verbose

    - name: Clippy
      run: cargo clippy
          
    - name: Run tests
      run: cargo test --workspace --verbose
