name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.80.1

      - name: Build
        run: cargo build --verbose

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.80.1

      - name: Run tests
        run: cargo test --workspace --verbose

  clippy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.80.1

      - name: Install clippy
        run: rustup component add clippy

      - name: Clippy
        run: cargo clippy

  build-docs:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4

      - name: Build Docs
        run: cargo doc --no-deps

      - name: Upload files
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/doc

  deploy-docs:
    runs-on: ubuntu-latest
    needs: [build-docs]

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
